### ISSUE TITLE
Question: Preventing false claims ...

### ISSUE THREAD

**Issue by srikumarks** [AigangNetwork/aigang-forwarder#2]
This is about the BatteryInsurancePolicy solidity code at the following line -

https://github.com/AigangNetwork/aigang-forwarder/blob/47d6919409ed6562275859318c6952c20d6b419b/contracts/BatteryInsurancePolicy.sol#L217

Is it not the case that the insured, after being validated by the insurer, can invoke the `claim(wearLevel)` call from the command line with whatever value they want and get their claim met even though their actual battery wear level is just fine? There seems to be no way in the contract to trust that the `wearLevel` being supplied by the insured is actually valid in order to release the claim. 

Am I missing something?

**Comment by dariusdev** [comment]
Hi srikumarks. Yes you can call this method when you want. These contracts are made only for demo purposes and not for real insurances
